<template>
    <div class="port-container">
        <el-card shadow="hover">
            <el-row style="margin-bottom: 20px;" :gutter="20">
                <el-col :span="6">
                    <div class="flex-box">
                        <span style="width: 80px;">时间标尺：</span>
                        <el-select filterable v-model="queryForm.timeScaleCategory" @change="queryData" clearable
                            placeholder="请选择">
                            <el-option v-for="item in categoryList" :key="item" :label="item" :value="item">
                            </el-option>
                        </el-select>
                    </div>
                </el-col>
                <el-col :span="6">
                    <div class="flex-box">
                        <span>显示天数：</span>
                        <el-select filterable v-model="queryForm.durationDay" @change="queryData" clearable
                            placeholder="请选择">
                            <el-option v-for="item in showDayList" :key="item" :label="item.label" :value="item.value">
                            </el-option>
                        </el-select>
                    </div>
                </el-col>
            </el-row>
            <el-row style="margin-bottom: 20px;" :gutter="20">
                <el-col :span="24" style="text-align: right;">
                    <el-button type="primary" :icon="Search" @click="queryData">查询</el-button>
                </el-col>
            </el-row>
            <div class="port-header">
                <h2>{{ queryForm.timeScaleCategory ? queryForm.timeScaleCategory : '' + '标尺信息' }}</h2>
                <div class="header-actions">
                </div>
            </div>
            <el-table :data="tableData" border style="width: 100%">
                <el-table-column label="编号" type="index" align="center" width="60" />
                <el-table-column prop="startHarbor" label="起始港" v-if="queryForm.timeScaleCategory === '长江航道航行时间'"
                    align="center" />
                <el-table-column prop="harbor"
                    :label="(queryForm.timeScaleCategory === '装港等泊时间' || queryForm.timeScaleCategory === '装港装船时间') ? '港口' :
                (queryForm.timeScaleCategory === '卸港等泊时间' || queryForm.timeScaleCategory === '卸港卸船时间') ? '自由电厂(等泊时间/小时)' : queryForm.timeScaleCategory === '航行时间' ? '自由电厂(航行时间/小时)' : '终点港'"
                    align="center" />
                <el-table-column v-for="(item, index) in columns" :key="index" align="center" :label="item.label"
                    :prop="item.prop">
                    <template #default="{ row, column, $index }">
                        <span>{{ queryForm.durationDay > index ? row[item.prop] : '' }}</span>
                    </template>
                </el-table-column>
            </el-table>
            <echartsData  :title="queryForm.timeScaleCategory" :data="tableData" />
        </el-card>
    </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { ElMessage } from 'element-plus'
import echartsData from './components/echarts-data.vue'
let showDayList = [
    { label: '近1天', value: 1 },
    { label: '近2天', value: 2 },
    { label: '近3天', value: 3 },
    { label: '近4天', value: 4 },
    { label: '近5天', value: 5 },
    { label: '近6天', value: 6 },
    { label: '近7天', value: 7 },
    { label: '近8天', value: 8 },
    { label: '近9天', value: 9 },
    { label: '近10天', value: 10 }
]
let columns = [
    {
        prop: 'one',
        label: '近1天',
        align: 'center'
    },
    {
        prop: 'two',
        label: '近2天',
        align: 'center'
    },
    {
        prop: 'three',
        label: '近3天',
        align: 'center'
    },
    {
        prop: 'four',
        label: '近4天',
        align: 'center'
    },
    {
        prop: 'five',
        label: '近5天',
        align: 'center'
    },
    {
        prop: 'six',
        label: '近6天',
        align: 'center'
    },
    {
        prop: 'seven',
        label: '近7天',
        align: 'center'
    },
    {
        prop: 'eight',
        label: '近8天',
        align: 'center'
    },
    {
        prop: 'nine',
        label: '近9天',
        align: 'center'
    },
    {
        prop: 'ten',
        label: '近10天',
        align: 'center'
    }
]
import { Search } from '@element-plus/icons-vue'
console.log('PortInfo 组件初始化')
const categoryList = ['航行时间', '装港等泊时间', '卸港等泊时间', '装港装船时间', '卸港卸船时间', '长江航道航行时间', '长江口停航时间']
const queryForm = reactive({
    timeScaleCategory: '装港等泊时间',
    startTime: '',
    endTime: '',
    durationDay: 10
})

const sel = ref({})
// 编辑港口
const handleEdit = (row) => {
    for (let i of tableData.value) {
        if (i.isSet) return ElMessage.error('请先保存当前编辑项')
    }
    sel.value = row
    row.isSet = true
}
const save = (row, index) => {
    if (!row.isSet) return
    let data = JSON.parse(JSON.stringify(sel.value))
    row.avg = average([data.one, data.two, data.three, data.four, data.five, data.six, data.seven, data.eight, data.nine, data.ten, data.Nov, data.Dec])
    row.isSet = false
}
const average = (numbers, decimalPlaces = 0) => {
    if (numbers.length === 0) return 0;
    const sum = numbers.reduce((acc, num) => acc + Number(num), 0);
    console.log(sum, numbers.length);
    const avg = sum / numbers.length;
    return Number(avg.toFixed(decimalPlaces));
}

const data = reactive([
    {
        title: '航行时间',
        data: [
            {
                harbor: '大开电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '鞍山电厂',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '舟山电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '太仓电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '宁波电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '常州电厂',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '泰州电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '宿迁电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '福州电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '泉州电厂',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '惠州电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '北海电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ],
        data1: [
            {
                harbor: '大开电厂',
                one: 70,
                two: 66,
                three: 90,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                harbor: '鞍山电厂',
                one: 80,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                harbor: '舟山电厂',
                one: 70,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 70,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                harbor: '太仓电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '宁波电厂',
                one: 100,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 59,
            },
            {
                harbor: '常州电厂',
                one: 24,
                two: 18,
                three: 90,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 90,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 45,
            },
            {
                harbor: '泰州电厂',
                one: 49,
                two: 80,
                three: 80,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 49,
            },
            {
                harbor: '宿迁电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '福州电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                harbor: '泉州电厂',
                one: 90,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                harbor: '惠州电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                harbor: '北海电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },
        ]
    },
    {
        title: '装港等泊时间',
        data: [
            {
                harbor: '曹妃甸',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '天津',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '秦皇岛',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '龙口',
                one: 90,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 90,
                avg: 38,
            },
            {
                harbor: '黄骅',
                one: 80,
                two: 52,
                three: 69,
                four: 51,
                five: 61,
                six: 51,
                seven: 65,
                eight: 67,
                nine: 69,
                ten: 67,
                Nov: 41,
                Dec: 80,
                avg: 63,
            },
            {
                harbor: '锦州',
                one: 70,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 70,
                avg: 39,
            },
            {
                harbor: '高栏',
                one: 60,
                two: 60,
                three: 10,
                four: 70,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 60,
                avg: 43,
            },
            {
                harbor: '京唐',
                one: 70,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 70,
                avg: 35,
            }],
        data1: [
            {
                harbor: '曹妃甸',
                one: 70,
                two: 66,
                three: 90,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                harbor: '天津',
                one: 80,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                harbor: '秦皇岛',
                one: 70,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 70,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                harbor: '龙口',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            }, {
                harbor: '黄骅',
                one: 71,
                two: 52,
                three: 69,
                four: 51,
                five: 61,
                six: 51,
                seven: 65,
                eight: 67,
                nine: 69,
                ten: 67,
                Nov: 41,
                Dec: 46,
                avg: 58,
            },
            {
                harbor: '锦州',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '高栏',
                one: 25,
                two: 20,
                three: 10,
                four: 70,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 60,
                avg: 36,
            },
            {
                harbor: '京唐',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            }]
    },
    {
        title: '卸港等泊时间',
        data: [
            {
                harbor: '蓬莱电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '费县发电厂',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '大开电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '庄河电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '宁波电厂',
                one: 100,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 59,
            },
            {
                harbor: '常州电厂',
                one: 24,
                two: 18,
                three: 90,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 90,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 45,
            },
            {
                harbor: '泰州电厂',
                one: 49,
                two: 80,
                three: 80,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 49,
            },
            {
                harbor: '宿迁电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '福州电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                harbor: '泉州电厂',
                one: 90,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                harbor: '惠州电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                harbor: '北海电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },],
        data1: [
            {
                harbor: '大开电厂',
                one: 70,
                two: 66,
                three: 90,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                harbor: '鞍山电厂',
                one: 80,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                harbor: '舟山电厂',
                one: 70,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 70,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                harbor: '太仓电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '宁波电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '常州电厂',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '泰州电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '宿迁电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '福州电厂',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '泉州电厂',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '惠州电厂',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '北海电厂',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ]
    },
    {
        title: '卸港卸船时间',
        data: [
            { "harbor": "蓬莱电厂", "one": "9", "two": "6", "three": "9", "four": "4", "five": "6", "six": "6", "seven": "3", "eight": "6", "nine": "9", "ten": "9", "Nov": "9", "Dec": "8", "avg": 7 },
            { "harbor": "蓬莱电厂", "one": "8", "two": "7", "three": "7", "four": "4", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "4", "ten": "7", "Nov": "8", "Dec": "4", "avg": 6 },
            { "harbor": "大开电厂", "one": "7", "two": "8", "three": "5", "four": "8", "five": "8", "six": "4", "seven": "7", "eight": "4", "nine": "3", "ten": "4", "Nov": "9", "Dec": "7", "avg": 6 },
            { "harbor": "庄河电厂", "one": "4", "two": "9", "three": "8", "four": "8", "five": "8", "six": "3", "seven": "9", "eight": "5", "nine": "7", "ten": "3", "Nov": "4", "Dec": "5", "avg": 6 },
        ],
        data1: [
            { "harbor": "蓬莱电厂", "one": "7", "two": "5", "three": "6", "four": "5", "five": "6", "six": "6", "seven": "6", "eight": "6", "nine": "6", "ten": "6", "Nov": "4", "Dec": "4", "avg": 6 },
            { "harbor": "蓬莱电厂", "one": "2", "two": "1", "three": "1", "four": "4", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "7", "ten": "9", "Nov": "6", "Dec": "4", "avg": 5 },
            { "harbor": "大开电厂", "one": "5", "two": "6", "three": "8", "four": "7", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "7", "ten": "8", "Nov": "6", "Dec": "6", "avg": 6 },
            { "harbor": "庄河电厂", "one": "5", "two": "9", "three": "7", "four": "6", "five": "8", "six": "7", "seven": "9", "eight": "6", "nine": "6", "ten": "7", "Nov": "4", "Dec": "5", "avg": 7 }]
    },
    {
        title: '装港装船时间',
        data: [
            { "harbor": "曹妃甸", "one": "9", "two": "6", "three": "9", "four": "4", "five": "6", "six": "6", "seven": "3", "eight": "6", "nine": "9", "ten": "9", "Nov": "9", "Dec": "8", "avg": 7 },
            { "harbor": "天津", "one": "8", "two": "7", "three": "7", "four": "4", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "4", "ten": "7", "Nov": "8", "Dec": "4", "avg": 6 },
            { "harbor": "秦皇岛", "one": "7", "two": "8", "three": "5", "four": "8", "five": "8", "six": "4", "seven": "7", "eight": "4", "nine": "3", "ten": "4", "Nov": "9", "Dec": "7", "avg": 6 },
            { "harbor": "龙口", "one": "4", "two": "9", "three": "8", "four": "8", "five": "8", "six": "3", "seven": "9", "eight": "5", "nine": "7", "ten": "3", "Nov": "4", "Dec": "5", "avg": 6 },
            { "harbor": "黄骅", "one": "7", "two": "9", "three": "9", "four": "9", "five": "6", "six": "6", "seven": "6", "eight": "6", "nine": "6", "ten": "6", "Nov": "4", "Dec": "4", "avg": 7 },
            { "harbor": "锦州", "one": "2", "two": "8", "three": "8", "four": "4", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "7", "ten": "9", "Nov": "6", "Dec": "4", "avg": 6 },
            { "harbor": "高栏", "one": "5", "two": "6", "three": "8", "four": "7", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "7", "ten": "8", "Nov": "6", "Dec": "6", "avg": 6 },
            { "harbor": "京唐", "one": "5", "two": "9", "three": "7", "four": "6", "five": "8", "six": "7", "seven": "9", "eight": "6", "nine": "9", "ten": "9", "Nov": "9", "Dec": "9", "avg": 8 }],
        data1: [{ "harbor": "曹妃甸", "one": "5", "two": "6", "three": "9", "four": "4", "five": "6", "six": "6", "seven": "3", "eight": "6", "nine": "4", "ten": "5", "Nov": "4", "Dec": "8", "avg": 6 }, { "harbor": "天津", "one": "8", "two": "1", "three": "1", "four": "4", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "4", "ten": "1", "Nov": "8", "Dec": "4", "avg": 4 }, { "harbor": "秦皇岛", "one": "7", "two": "3", "three": "5", "four": "3", "five": "3", "six": "4", "seven": "7", "eight": "4", "nine": "3", "ten": "4", "Nov": "9", "Dec": "7", "avg": 5 }, { "harbor": "龙口", "one": "4", "two": "9", "three": "2", "four": "2", "five": "2", "six": "3", "seven": "9", "eight": "5", "nine": "7", "ten": "3", "Nov": "4", "Dec": "5", "avg": 5 }, { "harbor": "黄骅", "one": "7", "two": "5", "three": "6", "four": "5", "five": "6", "six": "6", "seven": "6", "eight": "6", "nine": "6", "ten": "6", "Nov": "4", "Dec": "4", "avg": 6 }, { "harbor": "锦州", "one": "2", "two": "1", "three": "1", "four": "4", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "7", "ten": "9", "Nov": "6", "Dec": "4", "avg": 5 }, { "harbor": "高栏", "one": "5", "two": "6", "three": "8", "four": "7", "five": "4", "six": "3", "seven": "7", "eight": "8", "nine": "7", "ten": "8", "Nov": "6", "Dec": "6", "avg": 6 }, { "harbor": "京唐", "one": "5", "two": "9", "three": "7", "four": "6", "five": "8", "six": "7", "seven": "9", "eight": "6", "nine": "6", "ten": "7", "Nov": "4", "Dec": "5", "avg": 7 }]
    },
    {
        title: '长江航道航行时间',
        data: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                startHarbor: '长江口',
                harbor: '黄骅',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ],
        data1: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                one: 70,
                two: 66,
                three: 90,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                startHarbor: '长江口',
                harbor: '徐州',
                one: 80,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                startHarbor: '长江口',
                harbor: '秦皇岛',
                one: 70,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 70,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                one: 80,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 80,
                Dec: 80,
                avg: 40,
            }, {
                startHarbor: '长江口',
                harbor: '黄骅',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                one: 90,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },]
    },
    {
        title: '长江口停航时间',
        data: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                startHarbor: '长江口',
                harbor: '黄骅',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                one: 24,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ],
        data1: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                one: 70,
                two: 66,
                three: 90,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                startHarbor: '长江口',
                harbor: '徐州',
                one: 80,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                startHarbor: '长江口',
                harbor: '秦皇岛',
                one: 70,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 70,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                one: 80,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 31,
                Nov: 80,
                Dec: 80,
                avg: 40,
            },
            {
                startHarbor: '长江口',
                harbor: '黄骅',
                one: 63,
                two: 66,
                three: 80,
                four: 48,
                five: 60,
                six: 63,
                seven: 38,
                eight: 66,
                nine: 49,
                ten: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                one: 90,
                two: 18,
                three: 10,
                four: 44,
                five: 42,
                six: 33,
                seven: 75,
                eight: 18,
                nine: 47,
                ten: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                one: 49,
                two: 34,
                three: 56,
                four: 36,
                five: 31,
                six: 45,
                seven: 45,
                eight: 47,
                nine: 53,
                ten: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                one: 45,
                two: 29,
                three: 27,
                four: 25,
                five: 29,
                six: 23,
                seven: 29,
                eight: 22,
                nine: 23,
                ten: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },]
    }
])
const tableData = ref([])
let currentIndex = ref(0)
const queryData = () => {
    currentIndex.value ? currentIndex.value = 0 : currentIndex.value = 1
    if (!queryForm.timeScaleCategory) {
        tableData.value = []
    }
    data.forEach(item => {
        if (item.title === queryForm.timeScaleCategory) {
            console.log(item, queryForm.timeScaleCategory);
                tableData.value = item.data
        }
    })
}
queryData()
</script>

<style scoped>
.port-container {
    padding: 20px;
    /* background-color: #fff; */
}

.port-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}

.header-actions {
    display: flex;
    gap: 10px;
}

.flex-box {
    display: flex;
    align-items: center;
}

.flex-box span {
    width: 80px;
}

.w220 {
    width: 300px;
}

.el-select,
.el-date-picker,
.el-input {
    flex: 1 !important;
}

/deep/ .flex-box .el-input {
    flex: 1 !important;
}
</style>
