<template>
    <div class="port-container">
        <el-card shadow="hover">
            <el-row style="margin-bottom: 20px;" :gutter="20">
                <el-col :span="6">
                    <div class="flex-box">
                        <span style="width: 120px;">时间标尺：</span>
                        <el-select filterable v-model="queryForm.timeScaleCategory" @change="queryData" clearable
                            placeholder="请选择">
                            <el-option v-for="item in categoryList" :key="item" :label="item" :value="item">
                            </el-option>
                        </el-select>
                    </div>
                </el-col>
                <el-col :span="6">
                    <div class="flex-box">
                        <span>开始时间：</span>
                        <el-date-picker v-model="queryForm.startTime" type="year" style="display: 100%;"
                            value-format="YYYY" placeholder="选择日期">
                        </el-date-picker>
                    </div>
                </el-col>
                <el-col :span="6">
                    <div class="flex-box">
                        <span>结束时间：</span>
                        <el-date-picker v-model="queryForm.endTime" type="year" style="display: 100%;"
                            value-format="YYYY" placeholder="选择日期">
                        </el-date-picker>
                    </div>
                </el-col>
            </el-row>
            <el-row style="margin-bottom: 20px;">
                <el-col :span="24" style="text-align: right;">
                    <el-button type="primary" :icon="Search" @click="queryData">查询</el-button>
                </el-col>
            </el-row>
            <div class="port-header">
                <h2>{{ queryForm.timeScaleCategory ? queryForm.timeScaleCategory : '' + '标尺信息' }}</h2>
                <div class="header-actions">
                </div>
            </div>
            <el-table :data="tableData" border style="width: 100%">
                <el-table-column label="编号" type="index" align="center" width="60" />
                <el-table-column prop="startHarbor" label="起始港" v-if="queryForm.timeScaleCategory === '长江航道航行时间'"
                    align="center" />
                <el-table-column prop="harbor"
                    :label="(queryForm.timeScaleCategory === '装港等泊时间' || queryForm.timeScaleCategory === '装港装船时间') ? '港口' :
                (queryForm.timeScaleCategory === '卸港等泊时间' || queryForm.timeScaleCategory === '卸港卸船时间') ? '自由电厂(等泊时间/小时)' : queryForm.timeScaleCategory === '航行时间' ? '自由电厂(航行时间/小时)' : '终点港'"
                    align="center" />
                <el-table-column v-for="(item, index) in columns" :key="index" align="center" :label="item.label"
                    :prop="item.prop">
                    <template #default="{ row, column, $index }">
                        <span v-if="row.isSet && item.label != '全年均值'">
                            <el-input type="textarea" :rows="1" placeholder="请输入" v-model="sel[item.prop]">
                            </el-input>
                        </span>
                        <span v-else>{{ row[item.prop] }}</span>
                    </template>
                </el-table-column>
                <el-table-column prop="operation" label="操作" align="center" width="180">
                    <template #default="{ row, column, $index }">
                        <el-button link type="primary" @click="handleEdit(row)">编辑</el-button>
                        <el-button link type="primary" @click="save(row, $index)">保存</el-button>
                    </template>
                </el-table-column>
            </el-table>
        </el-card>
    </div>
</template>

<script setup>
import { ref, reactive } from 'vue'
import { ElMessage } from 'element-plus'

let columns = [
    {
        prop: 'Jan',
        label: '1月',
        align: 'center'
    },
    {
        prop: 'Feb',
        label: '2月',
        align: 'center'
    },
    {
        prop: 'Mar',
        label: '3月',
        align: 'center'
    },
    {
        prop: 'Apr',
        label: '4月',
        align: 'center'
    },
    {
        prop: 'May',
        label: '5月',
        align: 'center'
    },
    {
        prop: 'Jun',
        label: '6月',
        align: 'center'
    },
    {
        prop: 'Jul',
        label: '7月',
        align: 'center'
    },
    {
        prop: 'Aug',
        label: '8月',
        align: 'center'
    },
    {
        prop: 'Sep',
        label: '9月',
        align: 'center'
    },
    {
        prop: 'Oct',
        label: '10月',
        align: 'center'
    },
    {
        prop: 'Nov',
        label: '11月',
        align: 'center'
    },
    {
        prop: 'Dec',
        label: '12月',
        align: 'center'
    },
    {
        prop: 'avg',
        label: '全年均值',
        align: 'center'
    }
]
import { Search } from '@element-plus/icons-vue'
console.log('PortInfo 组件初始化')
const categoryList = ['航行时间', '装港等泊时间', '卸港等泊时间', '装港装船时间', '卸港卸船时间', '长江航道航行时间', '长江口停航时间']
const queryForm = reactive({
    timeScaleCategory: '装港等泊时间',
    startTime: '',
    endTime: '',
})

const sel = ref({})
// 编辑港口
const handleEdit = (row) => {
    for (let i of tableData.value) {
        if (i.isSet) return ElMessage.error('请先保存当前编辑项')
    }
    sel.value = row
    row.isSet = true
}
const save = (row, index) => {
    if (!row.isSet) return
    let data = JSON.parse(JSON.stringify(sel.value))
    row.avg = average([data.Jan, data.Feb, data.Mar, data.Apr, data.May, data.Jun, data.Jul, data.Aug, data.Sep, data.Oct, data.Nov, data.Dec])
    row.isSet = false
}
const average = (numbers, decimalPlaces = 0) => {
    if (numbers.length === 0) return 0;
    const sum = numbers.reduce((acc, num) => acc + Number(num), 0);
    console.log(sum, numbers.length);
    const avg = sum / numbers.length;
    return Number(avg.toFixed(decimalPlaces));
}

const data = reactive([
    {
        title: '航行时间',
        data: [
            {
                harbor: '大开电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '鞍山电厂',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '舟山电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '太仓电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '宁波电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '常州电厂',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '泰州电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '宿迁电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '福州电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '泉州电厂',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '惠州电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '北海电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ],
        data1: [
            {
                harbor: '大开电厂',
                Jan: 70,
                Feb: 66,
                Mar: 90,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                harbor: '鞍山电厂',
                Jan: 80,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                harbor: '舟山电厂',
                Jan: 70,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 70,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                harbor: '太仓电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '宁波电厂',
                Jan: 100,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 59,
            },
            {
                harbor: '常州电厂',
                Jan: 24,
                Feb: 18,
                Mar: 90,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 90,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 45,
            },
            {
                harbor: '泰州电厂',
                Jan: 49,
                Feb: 80,
                Mar: 80,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 49,
            },
            {
                harbor: '宿迁电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '福州电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                harbor: '泉州电厂',
                Jan: 90,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                harbor: '惠州电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                harbor: '北海电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },
        ]
    },
    {
        title: '装港等泊时间',
        data: [
            {
                harbor: '曹妃甸',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '天津',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '秦皇岛',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '龙口',
                Jan: 90,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 90,
                avg: 38,
            },
            {
                harbor: '黄骅',
                Jan: 80,
                Feb: 52,
                Mar: 69,
                Apr: 51,
                May: 61,
                Jun: 51,
                Jul: 65,
                Aug: 67,
                Sep: 69,
                Oct: 67,
                Nov: 41,
                Dec: 80,
                avg: 63,
            },
            {
                harbor: '锦州',
                Jan: 70,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 70,
                avg: 39,
            },
            {
                harbor: '高栏',
                Jan: 60,
                Feb: 60,
                Mar: 10,
                Apr: 70,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 60,
                avg: 43,
            },
            {
                harbor: '京唐',
                Jan: 70,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 70,
                avg: 35,
            }],
        data1: [
            {
                harbor: '曹妃甸',
                Jan: 70,
                Feb: 66,
                Mar: 90,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                harbor: '天津',
                Jan: 80,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                harbor: '秦皇岛',
                Jan: 70,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 70,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                harbor: '龙口',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            }, {
                harbor: '黄骅',
                Jan: 71,
                Feb: 52,
                Mar: 69,
                Apr: 51,
                May: 61,
                Jun: 51,
                Jul: 65,
                Aug: 67,
                Sep: 69,
                Oct: 67,
                Nov: 41,
                Dec: 46,
                avg: 58,
            },
            {
                harbor: '锦州',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '高栏',
                Jan: 25,
                Feb: 20,
                Mar: 10,
                Apr: 70,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 60,
                avg: 36,
            },
            {
                harbor: '京唐',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            }]
    },
    {
        title: '卸港等泊时间',
        data: [
            {
                harbor: '蓬莱电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '费县发电厂',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '大开电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '庄河电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '宁波电厂',
                Jan: 100,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 59,
            },
            {
                harbor: '常州电厂',
                Jan: 24,
                Feb: 18,
                Mar: 90,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 90,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 45,
            },
            {
                harbor: '泰州电厂',
                Jan: 49,
                Feb: 80,
                Mar: 80,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 49,
            },
            {
                harbor: '宿迁电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '福州电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                harbor: '泉州电厂',
                Jan: 90,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                harbor: '惠州电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                harbor: '北海电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },],
        data1: [
            {
                harbor: '大开电厂',
                Jan: 70,
                Feb: 66,
                Mar: 90,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                harbor: '鞍山电厂',
                Jan: 80,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                harbor: '舟山电厂',
                Jan: 70,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 70,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                harbor: '太仓电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 70,
                Dec: 70,
                avg: 35,
            },
            {
                harbor: '宁波电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '常州电厂',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '泰州电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '宿迁电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                harbor: '福州电厂',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                harbor: '泉州电厂',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                harbor: '惠州电厂',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                harbor: '北海电厂',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ]
    },
    {
        title: '卸港卸船时间',
        data: [
            { "harbor": "蓬莱电厂", "Jan": "9", "Feb": "6", "Mar": "9", "Apr": "4", "May": "6", "Jun": "6", "Jul": "3", "Aug": "6", "Sep": "9", "Oct": "9", "Nov": "9", "Dec": "8", "avg": 7 },
            { "harbor": "蓬莱电厂", "Jan": "8", "Feb": "7", "Mar": "7", "Apr": "4", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "4", "Oct": "7", "Nov": "8", "Dec": "4", "avg": 6 },
            { "harbor": "大开电厂", "Jan": "7", "Feb": "8", "Mar": "5", "Apr": "8", "May": "8", "Jun": "4", "Jul": "7", "Aug": "4", "Sep": "3", "Oct": "4", "Nov": "9", "Dec": "7", "avg": 6 },
            { "harbor": "庄河电厂", "Jan": "4", "Feb": "9", "Mar": "8", "Apr": "8", "May": "8", "Jun": "3", "Jul": "9", "Aug": "5", "Sep": "7", "Oct": "3", "Nov": "4", "Dec": "5", "avg": 6 },
        ],
        data1: [
            { "harbor": "蓬莱电厂", "Jan": "7", "Feb": "5", "Mar": "6", "Apr": "5", "May": "6", "Jun": "6", "Jul": "6", "Aug": "6", "Sep": "6", "Oct": "6", "Nov": "4", "Dec": "4", "avg": 6 },
            { "harbor": "蓬莱电厂", "Jan": "2", "Feb": "1", "Mar": "1", "Apr": "4", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "7", "Oct": "9", "Nov": "6", "Dec": "4", "avg": 5 },
            { "harbor": "大开电厂", "Jan": "5", "Feb": "6", "Mar": "8", "Apr": "7", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "7", "Oct": "8", "Nov": "6", "Dec": "6", "avg": 6 },
            { "harbor": "庄河电厂", "Jan": "5", "Feb": "9", "Mar": "7", "Apr": "6", "May": "8", "Jun": "7", "Jul": "9", "Aug": "6", "Sep": "6", "Oct": "7", "Nov": "4", "Dec": "5", "avg": 7 }]
    },
    {
        title: '装港装船时间',
        data: [
            { "harbor": "曹妃甸", "Jan": "9", "Feb": "6", "Mar": "9", "Apr": "4", "May": "6", "Jun": "6", "Jul": "3", "Aug": "6", "Sep": "9", "Oct": "9", "Nov": "9", "Dec": "8", "avg": 7 },
            { "harbor": "天津", "Jan": "8", "Feb": "7", "Mar": "7", "Apr": "4", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "4", "Oct": "7", "Nov": "8", "Dec": "4", "avg": 6 },
            { "harbor": "秦皇岛", "Jan": "7", "Feb": "8", "Mar": "5", "Apr": "8", "May": "8", "Jun": "4", "Jul": "7", "Aug": "4", "Sep": "3", "Oct": "4", "Nov": "9", "Dec": "7", "avg": 6 },
            { "harbor": "龙口", "Jan": "4", "Feb": "9", "Mar": "8", "Apr": "8", "May": "8", "Jun": "3", "Jul": "9", "Aug": "5", "Sep": "7", "Oct": "3", "Nov": "4", "Dec": "5", "avg": 6 },
            { "harbor": "黄骅", "Jan": "7", "Feb": "9", "Mar": "9", "Apr": "9", "May": "6", "Jun": "6", "Jul": "6", "Aug": "6", "Sep": "6", "Oct": "6", "Nov": "4", "Dec": "4", "avg": 7 },
            { "harbor": "锦州", "Jan": "2", "Feb": "8", "Mar": "8", "Apr": "4", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "7", "Oct": "9", "Nov": "6", "Dec": "4", "avg": 6 },
            { "harbor": "高栏", "Jan": "5", "Feb": "6", "Mar": "8", "Apr": "7", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "7", "Oct": "8", "Nov": "6", "Dec": "6", "avg": 6 },
            { "harbor": "京唐", "Jan": "5", "Feb": "9", "Mar": "7", "Apr": "6", "May": "8", "Jun": "7", "Jul": "9", "Aug": "6", "Sep": "9", "Oct": "9", "Nov": "9", "Dec": "9", "avg": 8 }],
        data1: [{ "harbor": "曹妃甸", "Jan": "5", "Feb": "6", "Mar": "9", "Apr": "4", "May": "6", "Jun": "6", "Jul": "3", "Aug": "6", "Sep": "4", "Oct": "5", "Nov": "4", "Dec": "8", "avg": 6 }, { "harbor": "天津", "Jan": "8", "Feb": "1", "Mar": "1", "Apr": "4", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "4", "Oct": "1", "Nov": "8", "Dec": "4", "avg": 4 }, { "harbor": "秦皇岛", "Jan": "7", "Feb": "3", "Mar": "5", "Apr": "3", "May": "3", "Jun": "4", "Jul": "7", "Aug": "4", "Sep": "3", "Oct": "4", "Nov": "9", "Dec": "7", "avg": 5 }, { "harbor": "龙口", "Jan": "4", "Feb": "9", "Mar": "2", "Apr": "2", "May": "2", "Jun": "3", "Jul": "9", "Aug": "5", "Sep": "7", "Oct": "3", "Nov": "4", "Dec": "5", "avg": 5 }, { "harbor": "黄骅", "Jan": "7", "Feb": "5", "Mar": "6", "Apr": "5", "May": "6", "Jun": "6", "Jul": "6", "Aug": "6", "Sep": "6", "Oct": "6", "Nov": "4", "Dec": "4", "avg": 6 }, { "harbor": "锦州", "Jan": "2", "Feb": "1", "Mar": "1", "Apr": "4", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "7", "Oct": "9", "Nov": "6", "Dec": "4", "avg": 5 }, { "harbor": "高栏", "Jan": "5", "Feb": "6", "Mar": "8", "Apr": "7", "May": "4", "Jun": "3", "Jul": "7", "Aug": "8", "Sep": "7", "Oct": "8", "Nov": "6", "Dec": "6", "avg": 6 }, { "harbor": "京唐", "Jan": "5", "Feb": "9", "Mar": "7", "Apr": "6", "May": "8", "Jun": "7", "Jul": "9", "Aug": "6", "Sep": "6", "Oct": "7", "Nov": "4", "Dec": "5", "avg": 7 }]
    },
    {
        title: '长江航道航行时间',
        data: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                startHarbor: '长江口',
                harbor: '黄骅',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ],
        data1: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                Jan: 70,
                Feb: 66,
                Mar: 90,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                startHarbor: '长江口',
                harbor: '徐州',
                Jan: 80,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                startHarbor: '长江口',
                harbor: '秦皇岛',
                Jan: 70,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 70,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                Jan: 80,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 80,
                Dec: 80,
                avg: 40,
            }, {
                startHarbor: '长江口',
                harbor: '黄骅',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                Jan: 90,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },]
    },
    {
        title: '长江口停航时间',
        data: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
            {
                startHarbor: '长江口',
                harbor: '黄骅',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 51,
                avg: 56,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                Jan: 24,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 26,
                Dec: 42,
                avg: 35,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 36,
                Dec: 57,
                avg: 44,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 40,
                Dec: 54,
                avg: 33,
            },
        ],
        data1: [
            {
                startHarbor: '长江口',
                harbor: '曹妃甸',
                Jan: 70,
                Feb: 66,
                Mar: 90,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 42,
                Dec: 88,
                avg: 61,
            },
            {
                startHarbor: '长江口',
                harbor: '徐州',
                Jan: 80,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 80,
                Dec: 42,
                avg: 42,
            },
            {
                startHarbor: '长江口',
                harbor: '秦皇岛',
                Jan: 70,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 70,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 90,
                Dec: 70,
                avg: 49,
            },
            {
                startHarbor: '长江口',
                harbor: '龙口',
                Jan: 80,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 31,
                Nov: 80,
                Dec: 80,
                avg: 40,
            },
            {
                startHarbor: '长江口',
                harbor: '黄骅',
                Jan: 63,
                Feb: 66,
                Mar: 80,
                Apr: 48,
                May: 60,
                Jun: 63,
                Jul: 38,
                Aug: 66,
                Sep: 49,
                Oct: 50,
                Nov: 80,
                Dec: 80,
                avg: 62,
            },
            {
                startHarbor: '长江口',
                harbor: '锦州',
                Jan: 90,
                Feb: 18,
                Mar: 10,
                Apr: 44,
                May: 42,
                Jun: 33,
                Jul: 75,
                Aug: 18,
                Sep: 47,
                Oct: 10,
                Nov: 90,
                Dec: 42,
                avg: 43,
            },
            {
                startHarbor: '长江口',
                harbor: '高栏',
                Jan: 49,
                Feb: 34,
                Mar: 56,
                Apr: 36,
                May: 31,
                Jun: 45,
                Jul: 45,
                Aug: 47,
                Sep: 53,
                Oct: 34,
                Nov: 80,
                Dec: 90,
                avg: 50,
            },
            {
                startHarbor: '长江口',
                harbor: '京唐',
                Jan: 45,
                Feb: 29,
                Mar: 27,
                Apr: 25,
                May: 29,
                Jun: 23,
                Jul: 29,
                Aug: 22,
                Sep: 23,
                Oct: 80,
                Nov: 80,
                Dec: 54,
                avg: 39,
            },]
    }
])
const tableData = ref([])
let currentIndex = ref(0)
const queryData = () => {
    currentIndex.value ? currentIndex.value = 0 : currentIndex.value = 1
    if (!queryForm.timeScaleCategory) {
        tableData.value = []
    }
    data.forEach(item => {
        if (item.title === queryForm.timeScaleCategory) {
            console.log(item, queryForm.timeScaleCategory);
            if (currentIndex.value === 0) {
                tableData.value = item.data1
            } else {
                tableData.value = item.data
            }
        }
    })
}
queryData()
</script>

<style scoped>
.port-container {
    padding: 16px;
    min-height: 100vh;
    /* background-color: #fff; */
}

.port-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 20px;
}

.header-actions {
    display: flex;
    gap: 10px;
}

.flex-box {
    display: flex;
    align-items: center;
}

.flex-box span {
    width: 80px;
}

.w220 {
    width: 300px;
}

.el-select,
.el-date-picker,
.el-input {
    flex: 1 !important;
}

/deep/ .flex-box .el-input {
    flex: 1 !important;
}
</style>
